---

- name: Ensure systemd reloaded
  ansible.builtin.service:
    daemon_reload: true

- name: Ensure Nextcloud services stopped
  ansible.builtin.service:
    name: "{{ item.name }}"
    state: stopped
  with_items: "{{ nextcloud_systemd_services_list | sort (attribute='priority', reverse=true) }}"

- name: Ensure Nextcloud services started
  ansible.builtin.service:
    name: "{{ item.name }}"
    state: started
    enabled: "{{ nextcloud_systemd_services_autostart_enabled }}"
  with_items: "{{ nextcloud_systemd_services_list | sort (attribute='priority') }}"
