---

- name: Ensure systemd reloaded
  ansible.builtin.service:
    daemon_reload: true

- name: Ensure Nextcloud services stopped
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ nextcloud_services_list }}"

- name: Ensure Nextcloud services started
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items: "{{ nextcloud_services_list }}"
