---

- include_tasks: "{{ role_path }}/tasks/server_base/setup_redhat.yml"
  when: ansible_os_family == 'RedHat'

- include_tasks: "{{ role_path }}/tasks/server_base/setup_debian.yml"
  when: ansible_os_family == 'Debian'

- include_tasks: "{{ role_path }}/tasks/server_base/setup_archlinux.yml"
  when: ansible_distribution == 'Archlinux'

- name: Ensure Docker is started and autoruns
  service:
    name: docker
    state: started
    enabled: yes

- name: "Ensure {{ nextcloud_ntpd_service }} is started and autoruns"
  service:
    name: "{{ nextcloud_ntpd_service }}"
    state: started
    enabled: yes
