---

- src: git+https://github.com/geerlingguy/ansible-role-docker
  version: 7.6.0
  name: geerlingguy.docker

- src: git+https://github.com/devture/com.devture.ansible.role.docker_sdk_for_python.git
  version: 129c8590e106b83e6f4c259649a613c6279e937a

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_help.git
  version: 7663e3114513e56f28d3ed762059b445c678a71a

- src: git+https://github.com/devture/com.devture.ansible.role.systemd_docker_base.git
  version: v1.4.1-0

- src: git+https://github.com/devture/com.devture.ansible.role.timesync.git
  version: v1.1.0-0

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_state_preserver.git
  version: ff2fd42e1c1a9e28e3312bbd725395f9c2fc7f16

- src: git+https://github.com/devture/com.devture.ansible.role.postgres.git
  version: v16.4-0

- src: git+https://github.com/devture/com.devture.ansible.role.postgres_backup.git
  version: 046004a8cb9946979b72ce81c2526c8033ea8067

- src: git+https://github.com/devture/com.devture.ansible.role.container_socket_proxy.git
  version: v0.1.2-1

- src: git+https://github.com/devture/com.devture.ansible.role.traefik.git
  version: v3.1.3-1

- src: git+https://github.com/devture/com.devture.ansible.role.systemd_service_manager.git
  version: v1.0.0-4

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_runtime_messages.git
  version: 9b4b088c62b528b73a9a7c93d3109b091dd42ec6
