---

nextcloud_collabora_document_server_enabled: false

nextcloud_collabora_document_server_domain: "collabora.{{ nextcloud_server_fqn_nextcloud }}"

nextcloud_collabora_document_server_container_image: "docker.io/collabora/code:22.05.10.1.1"

nextcloud_collabora_document_server_systemd_required_services_list: ['docker.service']
