- ansible.builtin.import_tasks: "{{ role_path }}/tasks/validate_config.yml"
  tags:
    - setup-nextcloud
    - setup-all

- ansible.builtin.import_tasks: "{{ role_path }}/tasks/setup.yml"
  tags:
    - setup-all
