---

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
  tags:
    - setup-all
    - setup-nextcloud
    - install-all
    - install-nextcloud

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup.yml"
  tags:
    - setup-all
    - install-all
