---

- name: Fail if required generic settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - nextcloud_generic_secret_key
    - nextcloud_architecture

- name: Fail if nextcloud_playbook_reverse_proxy_type is set incorrectly
  ansible.builtin.fail:
    msg: "Detected that variable nextcloud_playbook_reverse_proxy_type (current value: `{{ nextcloud_playbook_reverse_proxy_type }}`) appears to be set incorrectly. See roles/custom/nextcloud_playbook_base/defaults/main.yml for valid choices."
  when: nextcloud_playbook_reverse_proxy_type not in ['playbook-managed-traefik', 'playbook-managed-nginx', 'other-traefik-container', 'other-nginx-non-container', 'none']
