---

#
# Tasks related to setting up the Preview Generator app
# https://github.com/nextcloud/previewgenerator
#

- name: Ensure nextcloud-apache is started
  service: name=nextcloud-apache state=started daemon_reload=yes
  register: nextcloud_start

- name: Wait a while, so that Nextcloud can manage to start
  pause: seconds=7
  when: nextcloud_start.changed

- name: Install Preview-Generator app
  shell:
    cmd: "docker exec -u www-data nextcloud-apache php occ --no-warnings app:install previewgenerator"
  failed_when: false
  register: previewgenerator_install_result

- name: Fail if Preview-Generator failed to install
  fail:
    msg: "Preview-Generator failed to install. Full error: {{ previewgenerator_install_result }}"
  when: "previewgenerator_install_result.rc != 0 and previewgenerator_install_result.stdout != 'previewgenerator already installed'"

- name: Enable Preview-Generator app
  shell:
    cmd: "docker exec -u www-data nextcloud-apache php occ --no-warnings app:enable previewgenerator --force"
  failed_when: false

- name: Configure PreviewGenerator app
  shell:
    cmd: "docker exec -u www-data nextcloud-apache php occ --no-warnings config:app:set previewgenerator {{ item.key }} --value=\"{{ item.value }}\""
  with_items: "{{ nextcloud_previewgenerator_configurations }}"
  
# copy script file
- name: Ensure nextcloud-preview-generator script created
  template:
    src: "{{ role_path }}/templates/usr-local-bin/nextcloud-preview-generator.j2"
    dest: "/usr/local/bin/nextcloud-preview-generator"
    mode: 0750
    force: yes

# copy systemd service and timer files
- name: Ensure nextcloud-preview-generator.service installed
  template:
    src: "{{ role_path }}/templates/systemd/nextcloud-preview-generator.service.j2"
    dest: "/etc/systemd/system/nextcloud-preview-generator.service"
    mode: 0644
    force: yes

- name: Ensure nextcloud-preview-generator.timer installed
  template:
    src: "{{ role_path }}/templates/systemd/nextcloud-preview-generator.timer.j2"
    dest: "/etc/systemd/system/nextcloud-preview-generator.timer"
    mode: 0644
    force: yes

- name: Ensure nextcloud-preview-generator.timer is enabled
  systemd:
    name: nextcloud-preview-generator.timer
    enabled: yes
    state: started
    daemon_reload: yes

- name: Ensure nextcloud-preview-generator.service is started
  systemd:
    name: nextcloud-preview-generator.service
    state: started
    daemon_reload: yes
  when: "nextcloud_previewgenerator_enabled"

#
# Tasks related to getting rid of Preview Generator (if it was previously enabled)
#

- name: Ensure nextcloud-preview-generator.timer is removed if not enabled
  systemd:
    name: nextcloud-preview-generator.timer
    enabled: no
    state: stopped
    daemon_reload: yes
  when: "not nextcloud_previewgenerator_enabled"

- name: Ensure nextcloud-preview-generator.service is removed if not enabled
  systemd:
    name: nextcloud-preview-generator.service
    state: stopped
    daemon_reload: yes
  when: "not nextcloud_previewgenerator_enabled"

- name: Ensure files are removed
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/systemd/system/nextcloud-preview-generator.timer"
    - "/etc/systemd/system/nextcloud-preview-generator.service"
    - "/usr/local/bin/nextcloud-preview-generator"
  when: "not nextcloud_previewgenerator_enabled"

- name: Remove plugin
  shell:
    cmd: "docker exec -u www-data nextcloud-apache php occ --no-warnings app:remove previewgenerator"
  when: "not nextcloud_previewgenerator_enabled"
