---

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"
  tags:
    - setup-all
    - setup-appservice-slack

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_adjust_config.yml"
  tags:
    - setup-adjust-nextcloud-config
