---

- block:
    - when: nextcloud_fail2ban_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"
  tags:
    - setup-all
    - setup-fail2ban
    - install-all
    - install-fail2ban

- block:
    - when: not nextcloud_fail2ban_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  tags:
    - setup-all
    - setup-fail2ban
