---

- name: Remove fail2ban configuration
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/fail2ban/filter.d/nextcloud.conf
    - /etc/fail2ban/jail.d/nextcloud.local
