---

- block:
    - when: nextcloud_reverse_proxy_companion_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_install.yml"

    - when: not nextcloud_reverse_proxy_companion_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  tags:
    - setup-all
    - setup-nextcloud-reverse-proxy-companion
