---

- name: Ensure nextcloud-reverse-proxy-companion paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ nextcloud_user_uid }}"
    group: "{{ nextcloud_user_gid }}"
  with_items:
    - "{{ nextcloud_reverse_proxy_companion_base_path }}"
    - "{{ nextcloud_reverse_proxy_companion_config_path }}"

- name: Ensure nextcloud-reverse-proxy-companion support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ nextcloud_reverse_proxy_companion_base_path }}/{{ item }}"
    owner: "{{ nextcloud_user_uid }}"
    group: "{{ nextcloud_user_gid }}"
    mode: 0640
  with_items:
    - labels
    - nginx.conf

- name: Ensure nextcloud-reverse-proxy-companion nginx vhost configuration installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/nginx-conf.d/nextcloud.conf.j2"
    dest: "{{ nextcloud_reverse_proxy_companion_config_path }}/nextcloud.conf"
    owner: "{{ nextcloud_user_uid }}"
    group: "{{ nextcloud_user_gid }}"
    mode: 0640

- name: Ensure nextcloud-reverse-proxy-companion nginx container image is pulled
  community.docker.docker_image:
    name: "{{ nextcloud_reverse_proxy_companion_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure nextcloud-reverse-proxy-companion container network exists
  community.docker.docker_network:
    name: "{{ nextcloud_reverse_proxy_companion_container_network }}"

- name: Ensure nextcloud-reverse-proxy-companion.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/nextcloud-reverse-proxy-companion.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/nextcloud-reverse-proxy-companion.service"
    mode: 0640
  register: nextcloud_reverse_proxy_companion_systemd_service_result
