---

- name: Check existence of nextcloud-reverse-proxy-companion service
  ansible.builtin.stat:
    path: "/etc/systemd/system/nextcloud-reverse-proxy-companion.service"
  register: nextcloud_reverse_proxy_companion_service_stat

- when: nextcloud_reverse_proxy_companion_service_stat.stat.exists | bool
  block:
    - name: Ensure nextcloud-reverse-proxy-companion is stopped
      ansible.builtin.service:
        name: nextcloud-reverse-proxy-companion
        state: stopped
        daemon_reload: true

    - name: Ensure nextcloud-reverse-proxy-companion.service doesn't exist
      ansible.builtin.file:
        path: "/etc/systemd/system/nextcloud-reverse-proxy-companion.service"
        state: absent

    - name: Ensure nextcloud-reverse-proxy-companion data is removed
      ansible.builtin.file:
        path: "{{ nextcloud_reverse_proxy_companion_base_path }}"
        state: absent
