---

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_base.yml"
  tags:
    - setup-all
    - setup-nextcloud-nginx-proxy

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_ssl.yml"
  tags:
    - setup-all
    - setup-nextcloud-nginx-proxy
    - setup-nextcloud-nginx-proxy-ssl

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_nginx_proxy.yml"
  tags:
    - setup-all
    - setup-nextcloud-nginx-proxy
