---

- name: Ensure Nextcloud nginx-proxy paths exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: root
    group: root
  with_items:
    - "{{ nextcloud_nginx_proxy_base_path }}"
    - "{{ nextcloud_nginx_proxy_bin_path }}"
    - "{{ nextcloud_nginx_proxy_confd_path }}"
