---

- name: Ensure postgres data path exists
  file:
    path: "{{ nextcloud_postgres_data_path }}"
    state: directory
    mode: 0700
    owner: "{{ nextcloud_user_username }}"
    group: "{{ nextcloud_user_username }}"

- name: Ensure postgres Docker image is pulled
  docker_image:
    name: "{{ docker_postgres_image }}"

- name: Ensure Postgres environment variables file created
  template:
    src: "{{ role_path }}/templates/env/{{ item }}.j2"
    dest: "{{ nextcloud_environment_variables_data_path }}/{{ item }}"
    mode: 0640
  with_items:
    - "env-postgres-pgsql-docker"
    - "env-postgres-server-docker"

- name: Ensure nextcloud-postgres-cli script created
  template:
    src: "{{ role_path }}/templates/usr-local-bin/nextcloud-postgres-cli.j2"
    dest: "/usr/local/bin/nextcloud-postgres-cli"
    mode: 0750

- name: Ensure nextcloud-postgres.service installed
  template:
    src: "{{ role_path }}/templates/systemd/nextcloud-postgres.service.j2"
    dest: "/etc/systemd/system/nextcloud-postgres.service"
    mode: 0644
