---

- name: Ensure Nextcloud data path exists
  file:
    path: "{{ nextcloud_nextcloud_data_path }}"
    state: directory
    mode: 0755
    owner: "{{ nextcloud_user_username }}"
    group: "{{ nextcloud_user_username }}"

- name: Ensure Nextcloud Docker image is pulled
  docker_image:
    name: "{{ docker_nextcloud_image }}"

- name: Ensure nextcloud-apache.service installed
  template:
    src: "{{ role_path }}/templates/systemd/nextcloud-apache.service.j2"
    dest: "/etc/systemd/system/nextcloud-apache.service"
    mode: 0644

- name: Ensure periodic restarting of Nextcloud is configured (for SSL renewal)
  template:
    src: "{{ role_path }}/templates/cron.d/nextcloud-periodic-restarter.j2"
    dest: "/etc/cron.d/nextcloud-periodic-restarter"
    mode: 0600
