---

- name: Ensure Nextcloud nginx-proxy paths exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: root
    group: root
  with_items:
    - "{{ nextcloud_nginx_proxy_data_path }}"
    - "{{ nextcloud_nginx_proxy_confd_path }}"

- name: Ensure nginx Docker image is pulled
  docker_image:
    name: "{{ docker_nginx_image }}"

- name: Ensure Nextcloud proxy vhost configured
  template:
    src: "{{ role_path }}/templates/nginx-conf.d/{{ item }}.j2"
    dest: "{{ nextcloud_nginx_proxy_confd_path }}/{{ item }}"
    mode: 0644
  with_items:
    - "nextcloud-apache.conf"

- name: Allow access to nginx proxy ports in firewalld
  firewalld:
    service: "{{ item }}"
    state: enabled
    immediate: yes
    permanent: yes
  with_items:
    - "http"
    - "https"

- name: Ensure nextcloud-nginx-proxy.service installed
  template:
    src: "{{ role_path }}/templates/systemd/nextcloud-nginx-proxy.service.j2"
    dest: "/etc/systemd/system/nextcloud-nginx-proxy.service"
    mode: 0644
