---

- name: Allow access to HTTP/HTTPS in firewalld
  firewalld:
    service: "{{ item }}"
    state: enabled
    immediate: yes
    permanent: yes
  with_items:
    - http
    - https

- name: Ensure acmetool Docker image is pulled
  docker_image:
    name: willwill/acme-docker

# Granting +rx to others as well, because the `nginx` user from within
# nextcloud-nginx-proxy needs to be able to read the acme-challenge files inside
# for renewal purposes.
#
# This should not be causing security trouble outside of the container,
# as the parent directory (/nextcloud) does not allow "others" to access it or any of its children.
# Still, it works when the /ssl subtree is mounted in the container.
- name: Ensure SSL certificates path exists
  file:
    path: "{{ nextcloud_ssl_certs_path }}"
    state: directory
    mode: 0775
    owner: "{{ nextcloud_user_username }}"
    group: "{{ nextcloud_user_username }}"

- name: Check nextcloud-nginx-proxy state
  service: name=nextcloud-nginx-proxy
  register: nextcloud_nginx_proxy_state

- name: Ensure nextcloud-nginx-proxy is stopped (if previously installed & started)
  service: name=nextcloud-nginx-proxy state=stopped
  when: "nextcloud_nginx_proxy_state.status.ActiveState|default('missing') == 'active'"

- name: Ensure SSL certificates are marked as wanted in acmetool
  shell: >-
    /usr/bin/docker run --rm --name acmetool-host-grab -p 80:80
    -v {{ nextcloud_ssl_certs_path }}:/certs
    -e ACME_EMAIL={{ nextcloud_ssl_support_email }}
    willwill/acme-docker
    acmetool want {{ hostname_nextcloud }} --xlog.severity=debug

- name: Ensure nextcloud-nginx-proxy is started (if previously installed & started)
  service: name=nextcloud-nginx-proxy state=started
  when: "nextcloud_nginx_proxy_state.status.ActiveState|default('missing') == 'active'"

- name: Ensure periodic SSL renewal cronjob configured
  template:
    src: "{{ role_path }}/templates/cron.d/nextcloud-ssl-certificate-renewal.j2"
    dest: "/etc/cron.d/nextcloud-ssl-certificate-renewal"
    mode: 0600
