---

- block:
    - when: nextcloud_collabora_online_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_collabora_online_install.yml"
  tags:
    - setup-all
    - setup-collabora-online
    - install-all
    - install-collabora-online

- block:
    - when: not nextcloud_collabora_online_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_collabora_online_uninstall.yml"
  tags:
    - setup-all
    - setup-collabora-online

# This is meant to be executed subsequently, after Nextcloud is fully setup
- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/setup_collabora_app_install.yml"
  tags:
    - setup-collabora-app
    - install-collabora-app

- block:
    - ansible.builtin.include_tasks: "{{ role_path }}/tasks/configure_collabora_app.yml"
  tags:
    - setup-collabora-app
    - configure-collabora-app
