# Base directory that contains everything
nextcloud_base_path: "/nextcloud"

nextcloud_container_network: nextcloud

nextcloud_user_username: nextcloud
nextcloud_user_uid: 3991
nextcloud_user_gid: 3991

# nextcloud_systemd_services_list_auto contains a list of systemd services and their priorities.
# This list is managed by the playbook. You're not meant to override this variable.
# To add your own items to the list, use `nextcloud_systemd_services_list_additional`
nextcloud_systemd_services_list_auto: []

# nextcloud_systemd_services_list_additional contains your own list of systemd services and their priorities.
#
# Example:
# nextcloud_systemd_services_list_additional:
#   - name: some-service.service
#     priority: 1250
#   - name: another-service.service
#     priority: 3500
nextcloud_systemd_services_list_additional: []

# nextcloud_systemd_services_list contains a list of systemd services and their priorities.
nextcloud_systemd_services_list: "{{ nextcloud_systemd_services_list_auto + nextcloud_systemd_services_list_additional }}"

# nextcloud_systemd_services_autostart_enabled controls whether systemd services should auto-start when the system reboots
nextcloud_systemd_services_autostart_enabled: true

# The architecture that your server runs.
# Recognized values by us are 'amd64', 'arm32' and 'arm64'.
# Not all architectures support all services, so your experience (on non-amd64) may vary.
nextcloud_architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else ('arm64' if ansible_architecture == 'aarch64' else ('arm32' if ansible_architecture.startswith('armv') else '')) }}"

# A secret used as a base, for generating various other secrets.
# You can put any string here, but generating a strong one is preferred (e.g. `pwgen -s 64 1`).
nextcloud_generic_secret_key: ''
