---

- name: Ensure OnlyOffice path exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ nextcloud_user_uid }}"
    group: "{{ nextcloud_user_gid }}"
  with_items:
    - "{{ nextcloud_onlyoffice_document_server_base_path }}"
    - "{{ nextcloud_onlyoffice_document_server_log_path }}"

- name: Ensure OnlyOffice container image is pulled
  community.docker.docker_image:
    name: "{{ nextcloud_onlyoffice_document_server_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure nextcloud-onlyoffice-document-server.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/nextcloud-onlyoffice-document-server.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/nextcloud-onlyoffice-document-server.service"
    mode: 0644
